apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-nosigned
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/bgd/overlays/bgdk
    repoURL: http://gitea.apps.ocp4.rcarrata.com/gitea/ns-apps
    targetRevision: app-of-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
