apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netpol-deny-all
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: netpol/base
    repoURL: https://github.com/RedHat-EMEA-SSA-Team/ns-apps
    targetRevision: netpol
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
