apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simpson-ingress
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ingress/overlays/simpson/*
    repoURL: https://github.com/RedHat-EMEA-SSA-Team/ns-apps
    targetRevision: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
